Zakhar Kravchuk AVL Tree submission
zakr600/avl-set pull request #1
Opened 2022-03-19 15:29 UTC by zakr600

2022-03-20 20:35 UTC, Gleb-Tretyakov requested changes

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +#pragma once
убрать

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +#include <set>
отсортировать инклюды

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +struct node {
С большой буквы

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +    int height;
никаких int'ов не делаем

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +    node(const T& key) {
отступ

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        l = nullptr;
названия переменных

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        height = 1;
везде числа уносим в константы

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +int getHeight(node<T> *root) {
GetHieght и везде ниже

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +int getAVHeight(node<T> *root) {
тут сonst* можно?

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +void disc(node<T> *root) {
нейминг

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +void pull(node<T> *root) {
нейминг

2022-03-20 20:35 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +class Set {
Все функции унести в класс, сделать разделение private public, вспомогатиельных внекласса не нужно, зачем чтобы кто-то себе это импортил и пользовался

2022-03-30 16:37 UTC, zakr600 commented
https://official.contest.yandex.ru/contest/34590/run-report/66305766/

2022-03-30 16:42 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        Node* left_child;
инициализация всех переменных явно

2022-03-30 16:42 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        ~Node() {
Блин деструктор у структуры это не оч.
А нельзя delete как-то отельно делать?
Чтобы явно было видно методом, что чистим память

2022-03-30 16:42 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +                Node* a = FindMin(q);
во всех таких полотнах на 10 строк комментариев бы побольше че куда

2022-03-30 16:42 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +private:
Все кроме Node private надо после public.
Обычно всегда сначал public, потом пprivate, но Node придется
https://stackoverflow.com/questions/55201681/why-list-class-has-to-contain-a-node-struct-as-a-private-member-c

2022-03-30 16:59 UTC, zakr600 commented
https://official.contest.yandex.ru/contest/34590/run-report/66602252/

2022-04-06 17:03 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        Node(const Node& ot) {
oth тогда

2022-04-06 17:03 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +    ~Set() {
давай деструкторы хотя бы после конструкторов

2022-04-06 17:03 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +        Node* root;
а где явная инициализация + private section вниз

2022-04-06 17:03 UTC, Gleb-Tretyakov commented on task1/task1.cpp
> +            if (q == nullptr) {
Порядок if'ов такой нужен, что чем выше if тем чаще событие

2022-04-09 08:54 UTC, zakr600 commented
https://official.contest.yandex.ru/contest/34590/run-report/67066973/

2022-06-27 10:05 UTC, merged